# Generated by Django 5.2.5 on 2025-08-15 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_remove_usersubscription_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='start_date',
            field=models.DateField(),
        ),
    ]
