# Generated by Django 5.2.5 on 2025-08-15 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_alter_usersubscription_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='payment_proof',
            field=models.ImageField(blank=True, null=True, upload_to='payment_proofs/'),
        ),
    ]
