# Generated by Django 5.2.5 on 2025-08-15 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_remove_usersubscription_payment_proof_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subscriptions.subscriptionplan'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subscriptions.usersubscription'),
        ),
    ]
