# Generated by Django 5.2.5 on 2025-08-15 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0007_payment_plan_alter_payment_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersubscription',
            name='status',
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='is_canceled',
            field=models.BooleanField(default=False),
        ),
    ]
