# Generated by Django 5.2.5 on 2025-08-15 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0008_remove_usersubscription_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersubscription',
            name='is_canceled',
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Verification'), ('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('CANCELED', 'Canceled')], default='ACTIVE', max_length=20),
        ),
    ]
