# Generated by Django 5.2.5 on 2025-08-23 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0009_remove_usersubscription_is_canceled_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersubscription',
            name='status',
        ),
    ]
