# Generated by Django 5.2.5 on 2025-08-23 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0010_remove_usersubscription_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Verification'), ('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('CANCELED', 'Canceled')], default='ACTIVE', max_length=20),
        ),
    ]
